backend-api/config/routes.rb
BackendApi::Application.routes.draw do
  resources :units

  resources :people

end

backend-api/app/models/person.rb
class Person < ActiveRecord::Base
	validates :first_name, :last_name, :title, :email, presence: true
	belongs_to :unit
end

backend-api/app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :people 
end

backend-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

backend-api/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :unit_id, :type_id, :street_address_1, :street_address_2, :city, :state_id, :zipcode, :title, :phone, :email)
    end
end

backend-api/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

backend-api/app/helpers/application_helper.rb
module ApplicationHelper
end

backend-api/app/helpers/people_helper.rb
module PeopleHelper
end

backend-api/app/helpers/units_helper.rb
module UnitsHelper
end

backend-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackendApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

backend-api/app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :unit_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unit_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :street_address_1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street_address_1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :street_address_2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street_address_2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zipcode, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

backend-api/app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

backend-api/app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:unit_id) %></th>
      <th><%= model_class.human_attribute_name(:type_id) %></th>
      <th><%= model_class.human_attribute_name(:street_address_1) %></th>
      <th><%= model_class.human_attribute_name(:street_address_2) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state_id) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.unit_id %></td>
        <td><%= person.type_id %></td>
        <td><%= person.street_address_1 %></td>
        <td><%= person.street_address_2 %></td>
        <td><%= person.city %></td>
        <td><%= person.state_id %></td>
        <td><%= person.zipcode %></td>
        <td><%= person.title %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

backend-api/app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

backend-api/app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @person.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @person.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_id) %>:</strong></dt>
  <dd><%= @person.unit_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_id) %>:</strong></dt>
  <dd><%= @person.type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street_address_1) %>:</strong></dt>
  <dd><%= @person.street_address_1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:street_address_2) %>:</strong></dt>
  <dd><%= @person.street_address_2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @person.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state_id) %>:</strong></dt>
  <dd><%= @person.state_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zipcode) %>:</strong></dt>
  <dd><%= @person.zipcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @person.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @person.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

backend-api/app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                units_path, :class => 'btn' %>
  </div>
<% end %>

backend-api/app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

backend-api/app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.id, unit_path(unit) %></td>
        <td><%= unit.name %></td>
        <td><%=l unit.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_path,
            :class => 'btn btn-primary' %>

backend-api/app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

backend-api/app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @unit.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>